import { db } from "../../../prisma/db.js";

import type {
  CreateMemberInput,
  MemberListQuery,
  UpdateMemberInput,
} from "../member.types.js";
import { Temporal } from "temporal-polyfill";
import { pageOffset, paginationMeta } from "../../../utils/pagination.js";

/**
 * Find all members
 */
export const findAllMembers = async ({
  page,
  limit,
  status,
  sortBy,
  sortOrder,
}: MemberListQuery) => {
  const selectedMembers = db.orm.public.Member.select(
    "id",
    "memberId",
    "fullName",
    "fatherName",
    "motherName",
    "guardianName",
    "mobileNumber",
    "nidNumber",
    "email",
    "photoUrl",
    "occupation",
    "joinDate",
    "status",
    "notes",
    "createdAt",
    "updatedAt",
  );

  const filteredMembers = status
    ? selectedMembers.where({ status })
    : selectedMembers;

  const offset = pageOffset(page, limit);

  const membersQuery = (() => {
    switch (sortBy) {
      case "id":
        return filteredMembers.orderBy((member) =>
          sortOrder === "asc" ? member.id.asc() : member.id.desc(),
        );

      case "memberId":
        return filteredMembers.orderBy([
          (member) =>
            sortOrder === "asc"
              ? member.memberId.asc()
              : member.memberId.desc(),
          (member) => member.id.asc(),
        ]);

      case "fullName":
        return filteredMembers.orderBy([
          (member) =>
            sortOrder === "asc"
              ? member.fullName.asc()
              : member.fullName.desc(),
          (member) => member.id.asc(),
        ]);

      case "joinDate":
        return filteredMembers.orderBy([
          (member) =>
            sortOrder === "asc"
              ? member.joinDate.asc()
              : member.joinDate.desc(),
          (member) => member.id.desc(),
        ]);

      case "createdAt":
      default:
        return filteredMembers.orderBy([
          (member) =>
            sortOrder === "asc"
              ? member.createdAt.asc()
              : member.createdAt.desc(),
          (member) => member.id.desc(),
        ]);
    }
  })();

  const [{ total }, members] = await Promise.all([
    filteredMembers.aggregate((aggregate) => ({
      total: aggregate.count(),
    })),

    membersQuery.offset(offset).limit(limit).all(),
  ]);

  return {
    members,
    meta: paginationMeta(page, limit, total),
  };
};

/**
 * Find member by ID
 */
export const findMemberById = async (id: number) => {
  return db.orm.public.Member.select(
    "id",
    "memberId",
    "fullName",
    "fatherName",
    "motherName",
    "guardianName",
    "mobileNumber",
    "nidNumber",
    "email",
    "photoUrl",
    "occupation",
    "joinDate",
    "status",
    "notes",
    "createdAt",
    "updatedAt",
  ).first({ id });
};

/**
 * Find member by Member ID
 */
export const findMemberByMemberId = async (memberId: string) => {
  return db.orm.public.Member.select(
    "id",
    "memberId",
    "fullName",
    "mobileNumber",
    "status",
  ).first({ memberId });
};

/**
 * Find member by NID
 */
export const findMemberByNid = async (nidNumber: string) => {
  return db.orm.public.Member.select(
    "id",
    "memberId",
    "fullName",
    "nidNumber",
  ).first({ nidNumber });
};

export const updateMemberId = async (id: number, memberId: string) => {
  return db.orm.public.Member.where({ id })
    .select(
      "id",
      "memberId",
      "fullName",
      "fatherName",
      "motherName",
      "guardianName",
      "mobileNumber",
      "nidNumber",
      "email",
      "photoUrl",
      "occupation",
      "joinDate",
      "status",
      "notes",
      "createdAt",
      "updatedAt",
    )
    .update({
      memberId,
    });
};
/**
 * Create member
 *
 * memberId should be generated by the service/repository strategy.
 * addresses and guarantors are intentionally not passed directly
 * until relation creation is implemented.
 */
export const createMember = async (data: CreateMemberInput) => {
  return db.transaction(async (tx) => {
    // 1. Create member
    const member = await tx.orm.public.Member.select(
      "id",
      "memberId",
      "fullName",
      "fatherName",
      "motherName",
      "guardianName",
      "mobileNumber",
      "nidNumber",
      "email",
      "photoUrl",
      "occupation",
      "joinDate",
      "status",
      "notes",
      "createdAt",
      "updatedAt",
    ).create({
      fullName: data.fullName,
      fatherName: data.fatherName,
      motherName: data.motherName,
      guardianName: data.guardianName,
      mobileNumber: data.mobileNumber,
      nidNumber: data.nidNumber,
      email: data.email,
      photoUrl: data.photoUrl,
      occupation: data.occupation,

      joinDate: data.joinDate
        ? Temporal.Instant.from(data.joinDate.toISOString())
        : undefined,

      notes: data.notes,
    });

    // 2. Create addresses
    // PRESENT required
    // FATHER_HOME optional
    for (const address of data.addresses) {
      await tx.orm.public.MemberAddress.create({
        memberId: member.id,
        type: address.type,
        houseOrHolding: address.houseOrHolding,
        road: address.road,
        village: address.village,
        postOffice: address.postOffice,
        union: address.union,
        upazila: address.upazila,
        district: address.district,
        division: address.division,
      });
    }

    // 3. Create guarantors - optional
    if (data.guarantors?.length) {
      for (const guarantor of data.guarantors) {
        await tx.orm.public.Guarantor.create({
          memberId: member.id,
          fullName: guarantor.fullName,
          fatherName: guarantor.fatherName,
          motherName: guarantor.motherName,
          mobileNumber: guarantor.mobileNumber,
          nidNumber: guarantor.nidNumber,
          relationship: guarantor.relationship,

          houseOrHolding: guarantor.houseOrHolding,
          road: guarantor.road,
          village: guarantor.village,
          postOffice: guarantor.postOffice,
          union: guarantor.union,
          upazila: guarantor.upazila,
          district: guarantor.district,
          division: guarantor.division,

          occupation: guarantor.occupation,
          notes: guarantor.notes,
        });
      }
    }

    return member;
  });
};
/**
 * Update member
 */
export const updateMemberById = async (id: number, data: UpdateMemberInput) => {
  const {
    addresses: _addresses,
    guarantors: _guarantors,
    joinDate,
    ...memberData
  } = data;

  return db.orm.public.Member.where({
    id,
  })
    .select(
      "id",
      "memberId",
      "fullName",
      "fatherName",
      "motherName",
      "guardianName",
      "mobileNumber",
      "nidNumber",
      "email",
      "photoUrl",
      "occupation",
      "joinDate",
      "status",
      "notes",
      "createdAt",
      "updatedAt",
    )
    .update({
      ...memberData,

      ...(joinDate !== undefined && {
        joinDate: Temporal.Instant.from(joinDate),
      }),
    });
};

/**
 * Delete member
 */
export const deleteMemberById = async (id: number) => {
  return db.orm.public.Member.where({ id })
    .select("id", "memberId", "fullName", "mobileNumber", "status")
    .delete();
};
